### ISSUE TITLE
Pre-trained "D_latest.pth" model

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [richarduuz/Research_Project#5]
Hello, could you kindly send the pre-trained "D_latest.pth" model to my email lory.agnolucci@gmail.com? I would like to use your repo for a project of mine

**Comment by hhhharold** [comment]
> Hello, could you kindly send the pre-trained "D_latest.pth" model to my email [lory.agnolucci@gmail.com](mailto:lory.agnolucci@gmail.com)? I would like to use your repo for a project of mine

The model was trained on AWS server, but the server was closed. We cannot login in anymore to get any pre-trained weights.
